### ISSUE TITLE
Jean Kim Review Ticket Week 0 Github Pages

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#1]
Self Grade Score: 3/3
Crossover Score: 3/3
See below for details

**Comment by jeankim05** [comment]
Week 0 Review Ticket Github Pages
Total Self Grade: 3/3

Individual GitHub pages (3 points)

GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions
[Link to Github page with notes and actions](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
[Link to data structures page with link to replt and github](https://jeankim05.github.io/jeanapcsptri3/datastructures)
GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
[Link to create task page with information](https://jeankim05.github.io/jeanapcsptri3/createtask)

**Comment by Isaac-Le** [comment]
Crossover Grade by Isaac Le
Jean's Crossover Score 3/3

Individual GitHub pages (3 points)

GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions
[Link to Github page with notes and actions](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime
[Link to data structures page with link to replt and github](https://jeankim05.github.io/jeanapcsptri3/datastructures)
GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
[Link to create task page with information](https://jeankim05.github.io/jeanapcsptri3/createtask)

Has everything and is organized, nice and neat
