### ISSUE TITLE
Jean Kim Review Ticket Week 2 Classy Functions

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#4]
## Crossover Grade: 5.5/5 Graded by Isaac Le

**Comment by jeankim05** [comment]
Github Page that documents key learnings and code snippets using Github Pages and replit
- [x] Organize files, directories and menus for the first 3 weeks
[Link to organized repl.it with directories](https://replit.com/@JeanKim4/jeanapcsptri3#.replit)
- [x] Write Factorial function using classes and implementing call
[Link to factorial python file on repl.it](https://replit.com/@JeanKim4/jeanapcsptri3#week2/factorial.py)
- [x] Select your own Math function. Write it in Imperative and OOP form. 
[Link to greatest common factor math function file](https://replit.com/@JeanKim4/jeanapcsptri3#week2/mathfunction.py)
[Link to factors with Imperative and OOP format](https://replit.com/@JeanKim4/jeanapcsptri3#week2/factor.py)
- [x] Extra Credit.  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.
[Link to palindrome python page](https://replit.com/@JeanKim4/jeanapcsptri3#week2/palindrome.py)

-0.5 Missing some code comments and documentation throughout some of the files

**Comment by Isaac-Le** [comment]
Github Page that documents key learnings and code snippets using Github Pages and replit

 Organize files, directories and menus for the first 3 weeks
[Link to organized repl.it with directories](https://replit.com/@JeanKim4/jeanapcsptri3#.replit)
 Write Factorial function using classes and implementing call
[Link to factorial python file on repl.it](https://replit.com/@JeanKim4/jeanapcsptri3#week2/factorial.py)
 Select your own Math function. Write it in Imperative and OOP form.
[Link to greatest common factor math function file](https://replit.com/@JeanKim4/jeanapcsptri3#week2/mathfunction.py)
[Link to factors with Imperative and OOP format](https://replit.com/@JeanKim4/jeanapcsptri3#week2/factor.py)
 Extra Credit. Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.
[Link to palindrome python page](https://replit.com/@JeanKim4/jeanapcsptri3#week2/palindrome.py)

**Comment by Isaac-Le** [comment]
Github Page that documents key learnings and code snippets using Github Pages and replit

- [x]  Organize files, directories and menus for the first 3 weeks
[Link to organized repl.it with directories](https://replit.com/@JeanKim4/jeanapcsptri3#.replit)
- [x]  Write Factorial function using classes and implementing call
[Link to factorial python file on repl.it](https://replit.com/@JeanKim4/jeanapcsptri3#week2/factorial.py)
- [x]  Select your own Math function. Write it in Imperative and OOP form.
[Link to greatest common factor math function file](https://replit.com/@JeanKim4/jeanapcsptri3#week2/mathfunction.py)
[Link to factors with Imperative and OOP format](https://replit.com/@JeanKim4/jeanapcsptri3#week2/factor.py)
- [x]  Extra Credit. Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.
[Link to palindrome python page](https://replit.com/@JeanKim4/jeanapcsptri3#week2/palindrome.py)

-0.5 Not enough documentation and code comments in the files
