### ISSUE TITLE
Jean Kim Review Ticket Week 3 Algorithmic Final

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#5]
## Total Crossover Grade by Aadit: 10/10

Quality of work

- [x] Share link(s) on slack to final work: GitHub pages, Replit, Review Ticket(s), TimeBox, or other methods you have used to organize work.

Coding Review

Individual Coding:

- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [x]  GitHub commits you have made, show GitHub insights into your code commits.
- [x]  Show Code running on Replit as well as IntelliJ
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments
- [x] Show Crossover contribution: Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo
- [x] Show anything you have done to enhance what you have learned from Python code
- [x] Video 2 minutes: showing the above, quality suggested as follows

 Make sure you cover everything, but create your own order and optimize time
 Use Voice or Captions. Try not to wiggle mouse a lot or over scroll. Make sure you have a clear plan before you start.
 Perform video in small parts 15-30 seconds and finish a key subject. Then put the final Video together with Video editing or Youtube playlists.

Evidence

[Final Video](https://www.youtube.com/watch?v=w_IIscVg-Fw)
[Github Pages](https://jeankim05.github.io/jeanapcsptri3/)
[Aadit's Review Ticket for Crossover](https://github.com/aaditgupta21/csp-notes/issues/5)
[Crossover Commits](https://github.com/Isaac-Le/Tri3Repo/graphs/contributors)

**Comment by aaditgupta21** [comment]
- GitHub Pages showing key learnings and challenges conquered from Tech Talks
- GitHub commits you have made, show GitHub insights into your code commits
- Show Code running on Replit as well as IntelliJ
- Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- List and Loops: show runtime, code organization, code and comments
- Class review and understanding: show runtime, code organization, code and comments,
- Show Crossover contribution: Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their, GitHub repo. 
- Show anything you have done to enhance what you have learned from Python code 
- Video 2 minutes: showing the above, quality suggested as follows

Total 10/10. 
Great Video. It had all the requirements and was very descriptive. 

Twitter Video:
The video was great and very organized. The timestamps were great and helped me understand it very well.


- GitHub Pages showing key learnings and challenges conquered from Tech Talks
- GitHub commits you have made, show GitHub insights into your code commits
- Show Code running on Replit as well as IntelliJ
- Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- List and Loops: show runtime, code organization, code and comments
- Class review and understanding: show runtime, code organization, code and comments,
- Show Crossover contribution: Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their, GitHub repo. 
- Show anything you have done to enhance what you have learned from Python code 
- Video 2 minutes: showing the above, quality suggested as follows


Total 10/10.
