### ISSUE TITLE
Jean Kim Review Ticket Week 4: Accounts and Logins with Create Task

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#6]
**Final Grade for Jean Kim - 5/5**
**College Board Create Task (2 points)**
CB Create Task coding requirements documented
[Link to video](https://www.youtube.com/watch?v=9elTx5q5-Ps)
[Link to documentation of requirements on github pages](https://jeankim05.github.io/jeanapcsptri3/createtask)
Runtime of Code with comments on IntelliJ
[Link to code](https://github.com/Dylanluo05/Daji-Coders/blob/main/templates/foodquiz.html)
Screenshot of runtime on intellij
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/60992581/163845735-5bebdbb3-d5e9-43d3-852e-74e10d53c59f.png">

**Accounts and Logins Challenges for Jean and Jun (3 points)**
Hack 1 - Phone Number
[Link to CRUD page with updated phone number](https://github.com/jeankim05/nighthawk_csp/blob/master/cruddy/templates/cruddy/crud.html)
Hack 2 - Logout
[Link to page with logout function](https://github.com/jeankim05/nighthawk_csp/blob/master/cruddy/templates/cruddy/logout.html)
Hack 3 - Login Requirement
[Link to login requirement](https://github.com/jeankim05/nighthawk_csp/blob/master/frontend/frontend.py)

**Comment by Isaac-Le** [comment]
# 5/5 for Jean Kim
**College Board Create Task (2 points)**
CB Create Task coding requirements documented
[Link to video](https://www.youtube.com/watch?v=9elTx5q5-Ps)
[Link to documentation of requirements on github pages](https://jeankim05.github.io/jeanapcsptri3/createtask)
Runtime of Code with comments on IntelliJ
[Link to code](https://github.com/Dylanluo05/Daji-Coders/blob/main/templates/foodquiz.html)
Screenshot of runtime on intellij


**Accounts and Logins Challenges for Jean and Jun (3 points)**
Hack 1 - Phone Number
[Link to CRUD page with updated phone number](https://github.com/jeankim05/nighthawk_csp/blob/master/cruddy/templates/cruddy/crud.html)
Hack 2 - Logout
[Link to page with logout function](https://github.com/jeankim05/nighthawk_csp/blob/master/cruddy/templates/cruddy/logout.html)
Hack 3 - Login Requirement
[Link to login requirement](https://github.com/jeankim05/nighthawk_csp/blob/master/frontend/frontend.py)
