### ISSUE TITLE
Jean Kim Review Plan Week 5

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#7]
# Graded by Isaac Le Crossover and Self Grade Score: 5/5

Review ticket with Crossover Score on Monday 4/25 in class

- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18

**Monday**
- Crossover Review on Accounts and Logins 
- [Link to review ticket](https://github.com/jeankim05/jeanapcsptri3/issues/6)

**Tuesday**
- Take Proctored MCQ 1 (Score: 46/50)

**Wednesday**
- Review Proctored MCQ 1 and go over missed topics

**Thursday**
- Take Proctored MCQ 2 (Score: 44/50)

**Friday**
- Review Proctored MCQ 2 and go over missed topics

**Study Topics for Weeks before the AP Exam**
1.  Creativity
2. Abstraction
3. Data with bits, binary, hexadecimal and conversions
4. Algorithms
5. The Internet and Digital Divide

- [x] GH Indi Page with score and corrections
[Score and corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
 
- [x] Finals-Quiz1 46/50 and corrections
[Score and corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

- [x] Finals-Quiz2 44/50 and corrections
[Score and corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

- [x] Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permit
[Create Task Video/Code](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz)

**Comment by jeankim05** [comment]
Quiz 1 Corrections

Question 20
<img width="833" alt="image" src="https://user-images.githubusercontent.com/60992581/164951527-38912d32-dbd7-4ff0-adb9-5cc03b938491.png">
- I got this question wrong because I didn't realize that if both lists are sorted separately then combined, the new list that is combined will not be sorted. Therefore, option A is correct because both lists are combined and then sorted and duplicates removed.

**Comment by Isaac-Le** [comment]
## Crossover Grade: 5/5
Reason: He has everything nice, neat, and organized and also has everything nicely prepared.

Review ticket with Crossover Score on Monday 4/25 in class

- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18

**Monday**
- Crossover Review on Accounts and Logins 
- [Link to review ticket](https://github.com/jeankim05/jeanapcsptri3/issues/6)

**Tuesday**
- Take Proctored MCQ 1 (Score: 46/50)

**Wednesday**
- Review Proctored MCQ 1 and go over missed topics

**Thursday**
- Take Proctored MCQ 2 (Score: 44/50)

**Friday**
- Review Proctored MCQ 2 and go over missed topics

 
- [x] GH Indi Page with score and corrections
[Score and corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
 
- [x] Finals-Quiz1 46/50 and corrections
[Score and corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

- [x] Finals-Quiz2 44/50 and corrections
[Score and corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

- [x] Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permit
[Create Task Video/Code](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz)
