### ISSUE TITLE
Jean Kim Review Ticket Week 6: Proctored MCQ Week 2

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#8]
### Crossover Points given by Isaac Le - 4.5/5
**Points**

Acting Skit Improv (ASI)
- [x] Completed ASI activity with team, won donuts

MCQ Live Result
- [x] Scored 49/50 with one wrong answer, corrections linked [here](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

Review Ticket for Github Pages
- [x] [Link to updated github pages with all links and review tickets](https://jeankim05.github.io/jeanapcsptri3/)

**AP Tester Points**

Review Tickets
- [x] [Link to all review tickets including this one](https://jeankim05.github.io/jeanapcsptri3/)

Create Task and Review
- [x] [Link to create task](https://replit.com/@JeanKim4/cptjava)
- [x] [Link to code comments on create task](https://jeankim05.github.io/jeanapcsptri3/createtask)

**Comment by Isaac-Le** [comment]
**Crossover points 4.5/5**

Acting Skit Improv (ASI)
- [x] Completed ASI activity with team, won donuts

MCQ Live Result
- [x] Scored 49/50 with one wrong answer, corrections linked [here](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

Review Ticket for Github Pages
- [x] [Link to updated github pages with all links and review tickets](https://jeankim05.github.io/jeanapcsptri3/)

**AP Tester Points**

Review Tickets
- [x] [Link to all review tickets including this one](https://jeankim05.github.io/jeanapcsptri3/)

Create Task and Review
- [x] [Link to create task](https://replit.com/@JeanKim4/cptjava)
- [x] [Link to code comments on create task](https://jeankim05.github.io/jeanapcsptri3/createtask)
