### ISSUE TITLE
Jean Kim Review Ticket Week 7: AP Exams Week 1

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/jeanapcsptri3#9]
### Score given by Crossover Grader Isaac Le: 2/2
**Points: 2/2**
- [x] GH Indi Page, Review Ticket, Crossover graded, Study Plan
[Github Page](https://jeankim05.github.io/jeanapcsptri3/)
- [x] Quiz5 MCQ results >50%, (1 or 0) and test corrections (47/50)
[Quiz Corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)

**Comment by Isaac-Le** [comment]
**Crossover Grade: 2/2**
- [x] GH Indi Page, Review Ticket, Crossover graded, Study Plan
[Github Page](https://jeankim05.github.io/jeanapcsptri3/)
- [x] Quiz5 MCQ results >50%, (1 or 0) and test corrections (47/50)
[Quiz Corrections](https://jeankim05.github.io/jeanapcsptri3/testprepstudy)
